spring:
  application:
    name: backend
#  profiles:
#    active: dev

# Configuração do banco de dados
  datasource:
    url: jdbc:postgresql://db:5432/estacionamento # ${DB_URL}
    username: postgres # ${DB_USERNAME}
    password: root # ${DB_PASSWORD}
  # Configuração do Flyway
  flyway:
    enabled: true
    baseline-on-migrate: true

#  # Configurações do JPA básicas
#  jpa:
#    show-sql: true
#    format_sql: true
#    hibernate:
#      defer-datasource-initialization: true
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#      ddl-auto: create-drop


#  # Automatiza criação de script sql para backup e migrações
#  properties:
#    javax:
#      persistence:
#        schema-generation:
#          scripts:
#            action: create
#            create-target: src/main/resources/ddl.sql


# Caso eu queira implementar script de inicialização de dados
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:data.sql

# Configuração de prefixo de endpoints
server:
  servlet:
    context-path: /api