spring:
  application:
    name: backend
#  profiles:
#    active: dev

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}

  jpa:
    show-sql: true
    format_sql: true
    hibernate:
      defer-datasource-initialization: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create-drop

# Caso eu queira implementar script de inicialização de dados
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

server:
  servlet:
    context-path: /api