CREATE TABLE tb_usuario (
    id SERIAL NOT NULL PRIMARY KEY,
    login VARCHAR(100) NOT NULL UNIQUE,
    senha VARCHAR(100) NOT NULL,
    papel VARCHAR(20) NOT NULL CHECK (papel IN ('GERENTE', 'FUNCIONARIO', 'CLIENTE'))
);